# Generated by Django 3.0.3 on 2020-02-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_ame', models.CharField(max_length=50)),
                ('invoice_number', models.IntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_amount', models.IntegerField()),
            ],
        ),
    ]
