# Generated by Django 3.0.3 on 2020-02-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='contact_ame',
            new_name='contact_name',
        ),
    ]
